var controller = require('./controller.js');
var express = require('express');
var bodyParser = require('body-parser');
var sqlite3 = require('sqlite3').verbose();

var db = new sqlite3.Database('./data.db');
var app = express();

//set up port
app.set('port', process.env.PORT || 3003);

//set up static folder
app.use(express.static(__dirname + '/public'));
app.use(express.static(__dirname + '/images'));

//set body-parser to read post request data
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

//set up dispatcher
controller.dispatcher(app);

//create tables if don't exist
db.run("CREATE TABLE IF NOT EXISTS players (id integer PRIMARY KEY AUTOINCREMENT, username text NOT NULL UNIQUE, password text DEFAULT 'versicalabresi', image text, role text, sex text, biography text, mail text, address text, city text );");
db.run("CREATE TABLE IF NOT EXISTS championships (id integer PRIMARY KEY, type text NOT NULL, date datetime NOT NULL, organizer integer, name text, location integer, image text, in_progress integer NOT NULL, season integer NOT NULL, comment text, CONSTRAINT fk_players FOREIGN KEY (organizer) REFERENCES players(id) CONSTRAINT fk_locations FOREIGN KEY (location) REFERENCES locations(id));");
db.run("CREATE TABLE IF NOT EXISTS locations (id integer PRIMARY KEY AUTOINCREMENT, name text NOT NULL UNIQUE, image text, comment text);");
db.run("CREATE TABLE IF NOT EXISTS matches (id integer PRIMARY KEY, datetime datetime, team1 integer NOT NULL, team2 integer NOT NULL, to_be_played integer NOT NULL, team1_score integer, team2_score integer, CHECK((to_be_played == 0 AND team1_score IS NOT NULL AND team2_score IS NOT NULL) OR to_be_played == 1));");
db.run("CREATE TABLE IF NOT EXISTS championships_matches (id_championship integer NOT NULL, id_match integer NOT NULL, to_be_played integer NOT NULL, team1_points integer, team2_points integer, id_noticeboard integer NOT NULL, CONSTRAINT primary_keys PRIMARY KEY (id_championship, id_match), CONSTRAINT fk_championships FOREIGN KEY (id_championship) REFERENCES championships(id), CONSTRAINT fk_matches FOREIGN KEY (id_match) REFERENCES matches(id), CHECK((to_be_played == 0 AND team1_points IS NOT NULL AND team2_points IS NOT NULL) OR to_be_played == 1));");
db.run("CREATE TABLE IF NOT EXISTS championships_players (id_championship integer NOT NULL, id_player integer NOT NULL, place integer, score float, CONSTRAINT primary_keys PRIMARY KEY (id_championship, id_player), CONSTRAINT fk_championships FOREIGN KEY (id_championship) REFERENCES championships(id), CONSTRAINT fk_players FOREIGN KEY (id_player) REFERENCES players(id));");
db.run("CREATE TABLE IF NOT EXISTS championships_teams (id_championship integer NOT NULL, num_team integer NOT NULL, player1 integer, player2 integer, CONSTRAINT primary_keys PRIMARY KEY (id_championship, num_team), CONSTRAINT fk_championships FOREIGN KEY (id_championship) REFERENCES championships(id), CONSTRAINT fk_player1 FOREIGN KEY (player1) REFERENCES players(id), CONSTRAINT fk_player2 FOREIGN KEY (player2) REFERENCES players(id));");

//add records
// non so perché ma quando il db non esiste il codice sotto da errore
// per risolvere bisogna commentarlo tutto la prima volta e poi fare ripartire il 
// server dopo aver scommentato. Solo così funziona...
try {
  db.run("INSERT INTO players (id, username, password, image, role, sex, biography, mail, address, city) VALUES " + 
    "(1, 'Checco', 'versicalabresi', 'http://localhost:3003/profile.png', 'Ambivalente', 'M', 'Spericolato nelle giocate, come la sua preferita, la cannonata dal portiere; è difensore estroso col vizio del gol se gioca dietro e attaccante prolifico se gioca davanti. Si sottopone ad allenamenti estenuanti contro il parere di medici e famiglia  per arrivare sempre più tonico e imponente ai tornei in modo da intimorire gli avversari all’eventuale squizball da giocarsi chiaramente a torso nudo. Ossessionato dai suoi ricci, di una bellezza esagerata, I capelli vengono riempiti di almeno una decina di prodotti seguiti da attenzioni maniacali per ore al giorno. Contro questi vizi decisamente troppo moderni e mondani per un giocatore di calcino che dovrebbe dedicarsi unicamente al miglioramento della performance si schiera la matriarca della famiglia nonna Giuditta la quale ricorda spesso a Checco che assomigliare a “Nostro Signore” nei grandi slam del calcino, serve a poco.\nCuriosità: ha un fratello, Alessandro anch’egli professionista con il quale ha disputato sia in coppia sia come avversario diverse partite ufficiali.', NULL, NULL, NULL), " +
    "(2, 'Ale', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'Forse il giocatore più cresciuto e migliorato nel tempo, Bonzino si presenta oggi come uno dei migliori difensori del circuito. Solido, attento e con grande senso della posizione riesce a tenere livelli di concentrazione in grado di fiaccare qualsiasi attacco. Quando la squadra avversaria raggiunge il punteggio di 9 riesce ad aumentare a dismisura la propria determinazione per andare ad agguantare la squizball ed eventualmente, la vittoria.\nGli abitanti di Pisa hanno spesso il piacere di vederlo allenarsi sulle rive dell’Arno in compagnia della sua inseparabile canoa.\nCuriosità: ha un fratello, Francesco anch’egli professionista con il quale ha disputato sia in coppia sia come avversario diverse partite ufficiali.', NULL, NULL, NULL), " +
    "(3, 'Fede', 'versicalabresi', 'http://localhost:3003/profile.png', 'Attaccante', 'M', 'Insieme a Wilson tra i migliori marcatori della sua generazione, è dotato di velocità e potenza che gli permettono di mettere in difficoltà tutte le difese. Se costretto a giocare in difesa riesce a segnare anche da questa posizione.  é però spesso distratto in fase difensiva dove è vittima di errori che un portiere esperto non commetterebbe.\nOspita lo slam dell’alta bergullonia.\nControversie: risultato borderline ad alcuni valori in un test antidoping della federazione si è giustificato asserendo di fare uno sporadico uso di sostanze a scopo ricreativo. Per la giustizia sportiva il caso è ancora aperto.', NULL, NULL, NULL), " +
    "(4, 'Wilson', 'versicalabresi', 'http://localhost:3003/profile.png', 'Attaccante', 'M', 'Senza dubbio uno dei migliori giocatori in circolazione, Il Mirro cresce a pere e calcino fin da bambino, dovendo scegliere su quale di queste due passioni costruire la sua carriera agonistica, opta infine per il calciobalilla pur concedendosi ancora oggi qualche raccolta sporadica di William o di Abate.\nAttaccante imprevedibile e veloce, raffinato ma all’occasione potente, non esiste portiere che non lo tema. Quando costretto a giocare in porta si trasforma in difensore preciso e talvolta pericoloso anche offensivamente parlando.', NULL, NULL, NULL), " +
    "(5, 'Gambo', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'Lavoratore indefesso, si allena costantemente per migliorare le sue performance. Alla ricerca della miglior prestazione possibile, ha trovato in Punta Marina il luogo perfetto per i suoi allenamenti. Vi si reca infatti spesso per perfezionare continuamente lo stile di gioco. Non un caso che abbia scelto, insieme al fratello compagno di allenamenti, proprio Punta Marina come luogo di isolamento in attesa di negativizzarsi al Covid-19. Soprannominato Ballardini probabilmente per l’affinità fonetica con “biliardino”, gioca in casa l’unico Slam Outdoor del circus. Porta Romagna.', NULL, NULL, NULL), " +
    "(6, 'Chimico', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'Oberato di studio fin dalla nascita, e inizialmente riluttante alla partecipazione di tornei di questo nobile sport, il chimico riscopre nel calcino uno sfogo prezioso e con entusiasmo crescente si appassiona al professionismo fino a farne completamente parte. Portiere attento e, se in giornata, difficilmente penetrabile, è consigliabile non infastidirlo mentre si arriccia i corti capelli. Potrebbe infatti stare svolgendo una delle attività che più sono importanti per lui come l’acquisto di nuove calzature firmate sulla ultranota piattaforma di Jeff Bezos.', NULL, NULL, NULL), " +
    "(7, 'Macca', 'versicalabresi', 'http://localhost:3003/profile.png', 'Attaccante', 'M', 'Attaccante letale capace di rapidi movimenti che imprimono alla pallina alte velocità, Macca gioca in casa  uno degli slam del calcino più antichi, nel centro storico di Imola. Potrebbe facilmente migliorare le sue prestazioni se non avesse un vizio che con lo sport non va d’accordo, è infatti risaputo che sia “uno che beve”.', NULL, NULL, NULL), " +
    "(8, 'Gulli', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'Bergullese d’origine, Gulli si appassiona in tenera età al calcino sviluppando ben presto mani grandi e forti con cui ghermire le amate manopole. Non dotato di tecnica sopraffina o di particolare velocità sopperisce le sue mancanze con una volontà e determinazione d’acciaio e un cuore sconfinato. I suoi colpi speciali sono caricati a lungo arrotolando intorno alla stecca quasi tutto l’arto superiore e rilasciati a una velocità che non di rado infrange la barriera del suono lasciando storditi gli avversari e qualche volta anche il compagno di squadra. Insieme al connazionale bergullese Fede forma una coppia patriottica imbrobabile quanto efficace. Soffre particolarmente gli attacchi di Checco quando questi si palesano accompagnati dall’urlo di battaglia GULLIBAM!', NULL, NULL, NULL), " +
    "(9, 'Gollo', 'versicalabresi', 'http://localhost:3003/profile.png', 'Ambivalente', 'M', 'Estremamente attento nella preparazione muscolare, Gollo vanta tiri speciali di potenza non indifferente denominati da lui stesso “Bombate”. Non ha posizioni preferite sul campo da gioco, è solito infatti disertare le lezioni tattiche dei suoi allenatori preferendo a queste ultime eventi mondani o piaceri lussuriosi. ', NULL, NULL, NULL), " +
    "(10, 'Cami', 'versicalabresi', 'http://localhost:3003/profile.png', 'Attaccante', 'F', 'Unica rappresentante del gentil sesso a cimentarsi regolarmente nei tornei, Camilla non fa del suo punto di Forza la potenza o la velocità d’esecuzione quanto l’astuzia e l’imprevedibilità delle giocate. In grado di segnare a tutti i portieri in circolazione,  è dotata di un carattere piuttosto irascibile e burrascoso che la porta a condotte di gara accese e non sempre pacifiche, tanto che in carriera ha già ricevuto vari richiami disciplinari dalla FIGC (Federazione Italiana Giuoco Calcino).\nPunto debole: alle feste o ritrovi dove ci siano salatini non può avvicinarsi al calcino causa probabile presenza di noccioline o frutta a guscio che svolgono per Camilla la stessa funzione che la Kriptonite svolge per Superman.', NULL, NULL, NULL), " +
    "(11, 'Guido', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'Uno dei talenti scoperti più recentemente, è passato dal non giocare mai a comprare il proprio calcino e istituire uno degli slam più giocati, quello del LandiLand, confermando così i tre monti come zona caldissima del biliardino. Difensore concentrato, può tenere testa a tutti gli attaccanti. Ha scelto di fare esperienza fuori regione firmando un contratto annuale per una squadra milanese dove militerà per tutto il 2022.', NULL, NULL, NULL), " +
    "(12, 'Vero', 'versicalabresi', 'http://localhost:3003/profile.png', 'Attaccante', 'F', 'Classe 98, ha iniziato tardi la sua carriera agonistica ma grazie alle mani per suo coach sicuramente riuscirà a recuperare i gancini che le mancano per diventare una titolare, sfruttando anche la sua innata velocità che le ha conferito il soprannome “supersonica”. Ci riuscirà?', NULL, NULL, NULL), " +
    "(13, 'Pala', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'F', 'Chiara soprannominata la \"pala\", grande giocatrice dal talento ancora nascosto. Non ha avuto la possibilità di misurarsi nelle massime competizioni calcinistiche ma solo pochi sanno quali siano le sue incredibili doti nascoste. Giocatrice a cui la natura ha regalato un polso a dir poco \"bionico\". Con sguardi accattivanti e occhiolini fugaci distrae i sui avversari per non dover scoprire le sue carte. Attaccante talentuosa che non ha ancora trovato avversari alla sua altezza con i quali potersi misurare al massimo delle sue capacità. Ci aspettiamo molto da lei.', NULL, NULL, NULL), " +
    "(14, 'Maker', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'All’anagrafe il giocatore più esperto, tanto da meritarsi il soprannome di Attempted, è metalmeccanico nel tempo libero e alle prese con la rocambolesca compagine della Farmacia San Prospero come impiego principale. Ha mani magiche con cui riesce a costruire, creare, riparare, qualsiasi cosa. Non è un caso infatti che da queste stesse mani scaturiscano giocate importanti e decisive nei tornei più prestigiosi.', NULL, NULL, NULL), " +
    "(15, 'Aurora', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'F', 'Classe 98, è tra le poche rappresentati del gentil sesso tesserate presso la FIGC ( Federazione Italiana Giuoco Calcino). Anche se non è sempre presente alle competizioni, e quindi spesso fuori allenamento, dimostra una buona ambivalenza, anche se esprime il suo massimo potenziale nella posizione di difesa. Ama stare in squadra con Camilla e fa della chiacchiere il suo cavallo di battaglia per distrarre l’avversario. Famosa fino al 2019 per la sua grande abilità nella distruzione di cellulari speriamo che non inizi con i calcini.', NULL, NULL, NULL), " +
    "(16, 'Ace', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'M', 'A 8 anni ha fondato la sua prima startup è da sempre finanzia i migliori progetti in circolazione. Calcino Slam è l’ultimo investimento che lo Steve Jobs italiano ha avvolto tra le sue braccia. Le aspettative sono alte e lui, in quanto portiere rinomato, si sta prestando anche come uomo immagine per il prodotto.', NULL, NULL, NULL), " +
    "(17, 'Cate', 'versicalabresi', 'http://localhost:3003/profile.png', 'Portiere', 'F', 'Porta il cognome di un grande portiere del nostro circuito e non sarà un caso; Caterina Gambetti appare talvolta come una indifesa ragazza di città, che però tira fuori gli artigli quando si parla di calcino. Pare che il suo impegno cresca esponenzialmente quando in palio c’è un viaggio in qualche località balneare sull’oceano.', NULL, NULL, NULL), " +
    "(18, 'Juice', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'F', 'Forse il cane peggiore di tutti, è quello che dove lo metti NON sta. Sdazzo a non finire, soprattutto quando si tratta di bere o di rompere l’anima agli altri. È sempre contento senza motivo. Da dimenticare! Punto debole: è molto sensibile alle grufate del padrone su quel marcio naso.', NULL, NULL, NULL), " +
    "(19, 'Jack', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'M', 'Il king. Sebbene le forze comincino a venire meno e anche il cervello talvolta faccia brutti scherzi è ancora lì a comandare anche sui grufi più giovani, che gli portano un rispetto che non hanno neanche per i propri padroni umani. Curiosità: è possibile intravederlo completamente immobile per ore, senza alcun apparente motivo; è forse una antica tecnica di mimetismo insegnatagli dai suoi avi nell’800.', NULL, NULL, NULL), " +
    "(20, 'Pepe', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'M', 'Pepone nazionale, non ci sono altre descrizioni possibili. Un grufo con delle brutte esperienze con gli addestratori, è infatti quello con il peggior carattere in circolazione. Venera la sua padrona come neanche la Madonna e la assiste durante i lunghi periodi di degenza e convalescenza, come per esempio il Covid o il crociato.', NULL, NULL, NULL), " +
    "(21, 'Tea', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'F', 'Il cane dalla stazza più arrogante di tutti, questo grufo di petrolio fa letteramente il cazzo che vuole, pisciando in giro per casa e facendo i buchi nel giardino. Da dimenticare pure questo? Forse sì...', NULL, NULL, NULL), " + 
    "(22, 'Gina', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'F', 'Se sia un cane o un topo nessuno l’ha mai capito, ma è sempre contento di stare in braccio agli altri ed essere al centro dell’attenzione. Non arriva alle stecche del calcino, ma possiede la giusta grinta per compiere le imprese più impossibili, come questa.', NULL, NULL, NULL), " + 
    "(23, 'Fargo', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'M', 'Un grufo tutto d’un pezzo, enorme e a tratti solitario, si dice vada in giro con una fiaschetta di vodka sotto al collo. La velocità non sembra uno dei suoi punti di forza, ma mai dire mai...', NULL, NULL, NULL), " +
    "(24, 'Laika', 'versicalabresi', 'http://localhost:3003/profile.png', 'Grufo', 'F', 'Soprannominato ’Il Pulcioso’ è famoso per fare solo un bagno all'anno, rigorosamente nella pozza dei maiali. Lo si può intravedere girare come uno zombie presso Villa Mirandola, sia d'estate che d'inverno.', NULL, NULL, NULL); ");
  db.run("INSERT INTO locations (id, name, image, comment) VALUES (1, 'Alta Bergullonia', '../locations/1.png', ''), (2, 'Imola Centro Storico', '../locations/2.png', ''), (3, 'Landiland', '../locations/3.png', ''), (4, 'Tiro A Segno', '../locations/4.png', ''), (5, 'Porta Romagna', '../locations/5.png', ''), (6, 'Cuccia', '../locations/6.png', '');");  
} catch (error) {
  console.log("Insertion error...")
}
db.close()

//start server
app.listen(app.get('port'), '127.0.0.1', function () {
  console.log('UniboClendar started on http://127.0.0.1:' +
    app.get('port') + '; press Ctrl-C to terminate.');
});