name: Build iOS app
on: [push]
jobs:
  build:
    needs: install_deps
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          cd CalcinoSlamApp
          npm i
          npm run ios
